spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bolaofc}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:682412}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:bolaofc-secret-key}
football.api.key=${FOOTBALL_API_KEY:8dbdd134f47f4d0bb8b24ef02d60dc4d}
football.api.url=${FOOTBALL_API_URL:https://api.football-data.org/v4}