spring.datasource.url=jdbc:postgresql://localhost:5432/bolaofc
spring.datasource.username=postgres
spring.datasource.password=682412

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
api.security.token.secret=bolaofc-secret-key

football.api.key=8dbdd134f47f4d0bb8b24ef02d60dc4d
football.api.url=https://api.football-data.org/v4
